# Generated by Django 5.2 on 2025-04-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamiento',
            name='dosis',
            field=models.IntegerField(choices=[(1, '5mg'), (2, '10mg'), (3, '25mg'), (4, '50mg'), (5, '100mg'), (6, '200mg')]),
        ),
    ]
